### PR TITLE
23 component system

### PR DESCRIPTION
**Pull request by ZoeTheFox**
I mean, it's pretty much done. Will get more in depth when i start work for the actual systems behind the components.

### CODE REVIEW

**Review by kirilft — COMMENTED** [review]
looks great, waffels are sweet

**Review by kirilft — COMMENTED** [review]
i tried so hard´, and got so far, in the end it doesnt even matter

**Comment by ZoeTheFox** [comment]
> i tried so hard´, and got so far, in the end it doesnt even matter

Untitled

**Review by kirilft — APPROVED** [review]
it does matter

**Pull request merged**
